### ISSUE TITLE
make error (l64)

### ISSUE THREAD

**Issue by gibacic** [dmarienko/kdbml#1]
I couldn't compile this on my (Arch) Linux 4.8.13-1 x86_64 system because the Makefile had spaces instead of hard tabs.

It works just great when I edited the makefile to use semicolons. For example, I changed
```
%.o: %c
    ${CC} ${CFLAGS} -c -o$@ $<
```
to this working version:
```
%.o: %c; ${CC} ${CFLAGS} -c -o$@ $<
```
etc.

By the way, thanks for this package,
g

**Comment by dmarienko** [comment]
Thanks for catch, Goran. Fixed.
